#!/bin/bash

if (( ${BLOCK_BUTTON:-0} == 1 )); then
  pulsemixer --change-volume '-5'
elif (( ${BLOCK_BUTTON:-0} == 2 )); then
  pulsemixer --toggle-mute
elif (( ${BLOCK_BUTTON:-0} == 3 )); then
  pulsemixer --change-volume '+5'
fi

if (( $(pulsemixer --get-mute) == 1 )); then
  echo " MUTE"
  echo
  echo '#fbcf4b'
  exit 0
fi
  
VOLUME=$(pulsemixer --get-volume | awk '{print $1}')
if (( $VOLUME > 70 )); then
  echo " ${VOLUME}%"
elif (( $VOLUME > 20 )); then
  echo " ${VOLUME}%"
else
  echo " ${VOLUME}%"
fi
