#!/bin/zsh

OUTSIDE_ID=59641
INSIDE_ID=67039

if [[ "$1" == "in" ]]; then
  ID=$INSIDE_ID
  ICON=""
else
  ID=$OUTSIDE_ID
  ICON=""
fi

READINGS=($(curl "http://purpleair.com/json?show=${ID}" 2>/dev/null \
    | json_pp | grep 'Stats' | sed -e 's/.*v1\\":\([^,]*\).*/\1/'))

if (( ${#READINGS[@]} == 2 )); then
  PM2_5=$(( (${READINGS[1]} + ${READINGS[2]}) / 2 ))
else
  PM2_5=${READINGS[1]}
fi

# See https://forum.airnowtech.org/t/the-aqi-equation/169
#
# PM2.5               | ConcLo | ConcHi | AQILo | AQIHi
# Good                | 0.0    | 12.0   | 0     | 50
# Moderate            | 12.1   | 35.4   | 51    | 100
# Unhealthy Sensitive | 35.5   | 55.4   | 101   | 150
# Unhealthy           | 55.5   | 150.4  | 151   | 200
# Very Unhealthy      | 150.5  | 250.4  | 201   | 300
# Hazardous           | 250.5  | 500.4  | 301   | 500
#
# (AQIHi - AQILo) / (ConcHi - ConcLo) * (ConcNow - ConcLo) + AQILo

local AQI RATING
if (( $PM2_5 < 12.1 )); then
  AQI=$( printf "%.0f" $(( (50.0 - 0.0) / (12.0 - 0.0) * ($PM2_5 - 0.0) + 0.0 )) )
  RATING="#85df56" # green
elif (( $PM2_5 < 35.5 )); then
  AQI=$( printf "%.0f" $(( (100.0 - 51.0) / (35.4 - 12.1) * ($PM2_5 - 12.1) + 51 )) )
  RATING="#fbcf4b" # yellow
elif (( $PM2_5 < 55.5 )); then
  AQI=$( printf "%.0f" $(( (150.0 - 101.0) / (55.4 - 35.5) * ($PM2_5 - 35.5) + 101 )) )
  RATING="#f28c33" # orange
elif (( $PM2_5 < 150.5 )); then
  AQI=$( printf "%.0f" $(( (200.0 - 151.0) / (150.4 - 55.5) * ($PM2_5 - 55.5) + 151 )) )
  RATING="#dd4d3c" # red
elif (( $PM2_5 < 250.5 )); then
  AQI=$( printf "%.0f" $(( (300.0 - 201.0) / (250.4 - 150.5) * ($PM2_5 - 150.5) + 201 )) )
  RATING="#cf79e0" # purple
else
  AQI=$( printf "%.0f" $(( (500.0 - 301.0) / (500.4 - 250.5) * ($PM2_5 - 250.5) + 301 )) )
  RATING="#9b2f6a" # maroon
fi

echo "${ICON} ${AQI}"
echo
echo "${RATING}"
